import shutil
import subprocess
import webbrowser
from pathlib import Path

from invoke.context import Context
from invoke.tasks import task

# ================ Config ================= #
RELEASE_BRANCH = "main"  # reference branch for releases
CLEAN_DIRS: list[str] = [
    "build",  # Build artefacts
    "dist",  # Packaged distributions
    "htmlcov",  # HTML coverage report (pytest-cov)
    "docs/build",  # Sphinx build output
    "docs/code/api",  # API pages generated by sphinx-apidoc
    ".pytest_cache",  # pytest cache
    ".ruff_cache",  # Ruff cache
    ".mypy_cache",  # mypy cache
    ".okflint",  # JSON audit reports (regeneratable)
    "__pycache__",  # Python cache (root)
]
# Fichiers supprimés séparément : rmtree échoue sur un fichier, et
# ignore_errors=True masquerait l'échec sans rien nettoyer.
CLEAN_FILES: list[str] = [
    ".coverage",  # pytest-cov coverage data
    "coverage.xml",  # XML coverage report
]


@task
def clean(c: Context) -> None:
    """Remove build artifacts, generated docs and caches."""
    for directory in CLEAN_DIRS:
        path: Path = Path(directory)
        if path.is_dir():
            print(f"  - Removing {directory}/")
            shutil.rmtree(path, ignore_errors=True)

    for filename in CLEAN_FILES:
        file_path = Path(filename)
        if file_path.is_file():
            print(f"  - Removing {filename}")
            file_path.unlink(missing_ok=True)

    # Recursively clean __pycache__
    for path in Path(".").rglob("__pycache__"):
        print(f"  - Removing {path}")
        shutil.rmtree(path, ignore_errors=True)

    # Clean *.egg-info
    for path in Path(".").rglob("*.egg-info"):
        print(f"  - Removing {path}")
        shutil.rmtree(path, ignore_errors=True)

    # Clean .pyc files
    for path in Path(".").rglob("*.pyc"):
        print(f"  - Removing {path}")
        path.unlink(missing_ok=True)

    print("🗑 Clean task Done!")


@task
def index(c: Context) -> None:
    """Index the codebase in codebase-memory-mcp to improve Claude Code context.

    Uses the CLI mode of the codebase-memory-mcp binary to index the current
    project into the persistent knowledge graph. The index survives session
    restarts and allows Claude Code to make structural queries
    (call graph, dependencies, etc.) with ~99% fewer tokens than a file-by-file
    exploration.

    Re-run after every significant change to the codebase.
    """
    import json

    binary = Path(
        r"C:\Users\matth\AppData\Local\Programs\codebase-memory-mcp\codebase-memory-mcp.exe"
    )
    if not binary.exists():
        print(f"❌ codebase-memory-mcp binary not found: {binary}")
        print("   Install from: https://github.com/DeusData/codebase-memory-mcp")
        return

    repo_path = str(Path.cwd()).replace("\\", "/")
    payload = json.dumps({"repo_path": repo_path})

    print("🧠 Indexing codebase in codebase-memory-mcp...")
    print(f"   Project: {repo_path}")
    result = subprocess.run(
        [str(binary), "cli", "index_repository", payload],
        shell=False,
    )
    if result.returncode == 0:
        print("✅ Index updated. Claude Code can now query the knowledge graph.")
    else:
        print("❌ Indexing failed.")


@task
def lint(c: Context) -> None:
    """Run all quality checks via pre-commit (single source of truth)."""
    print("🔎 Running pre-commit on all files...")
    result = subprocess.run("uv run pre-commit run --all-files", shell=True)
    if result.returncode != 0:
        print("❌ Linting issues found!")
        raise SystemExit(result.returncode)
    print("✅ Linting Task Done!")


@task
def precommit_install(c: Context) -> None:
    """Install the pre-commit hooks (pre-commit and commit-msg stages).

    Both stages are required: the commitizen hook only fires on commit-msg,
    which pre-commit does not install by default.
    """
    print("🔧 Installing pre-commit hooks...")
    result = subprocess.run(
        "uv run pre-commit install --install-hooks -t pre-commit -t commit-msg",
        shell=True,
    )
    if result.returncode != 0:
        print("❌ pre-commit install failed!")
        raise SystemExit(result.returncode)
    print("✅ pre-commit hooks installed!")


@task
def test(c: Context, verbose: bool = False, coverage: bool = True) -> None:
    """Run the pytest test suite."""
    print("🧪 Running test suite...")

    # Build the command
    cmd = "uv run python -m pytest"
    if verbose:
        cmd += " -v"
    if not coverage:
        # pyproject.toml enables coverage by default via addopts
        cmd += " --no-cov"

    # Execute
    result = subprocess.run(cmd, shell=True)
    if result.returncode != 0:
        print("❌ Tests failed!")
        raise SystemExit(result.returncode)

    print("✅ All tests passed!")
    html_report = Path("htmlcov") / "index.html"
    if html_report.exists():
        print(f"📊 HTML report: {html_report.resolve()}")


@task
def docs(c: Context, open_browser: bool = False) -> None:
    """Build the Sphinx documentation as HTML.

    API pages are (re)generated automatically by the `builder-inited` hook
    declared in docs/code/conf.py, so this task does not call sphinx-apidoc
    itself: one single source of truth, so CI (which invokes sphinx-build
    directly) never publishes an amputated API doc.

    `-W --keep-going` reproduces CI's behavior: any warning becomes an
    error, but the build runs to completion so all of them get reported.
    """
    src = Path("docs/code")
    out = Path("docs/build") / "html"
    out.mkdir(parents=True, exist_ok=True)

    print("📖 Building Sphinx documentation...")
    result = subprocess.run(
        f'uv run sphinx-build -W --keep-going -b html "{src}" "{out}"',
        shell=True,
    )
    if result.returncode != 0:
        print("❌ Sphinx build failed!")
        raise SystemExit(result.returncode)

    index_html = out / "index.html"
    print(f"✅ Documentation built: {index_html.resolve()}")

    # Optionally open in browser
    if open_browser:
        webbrowser.open(index_html.as_uri())


@task
def build(c: Context) -> None:
    """Build the package (wheel + sdist) via uv."""
    print("📦 Building package...")
    result = subprocess.run("uv build", shell=True)
    if result.returncode != 0:
        print("❌ Build failed!")
        raise SystemExit(result.returncode)
    print("✅ Build Done! Artifacts in dist/")


@task
def release(
    c: Context,
    part: str | None = None,
    dry_run: bool = False,
    skip_tests: bool = False,
) -> None:
    """Orchestrate a release: bump version, changelog, commit, tag, push.

    Sequence:
      1. Verify we are on the main branch with a clean working tree
      2. Run lint + tests (safety before publishing) — unless --skip-tests
      3. Bump the version via commitizen. Without --part, commitizen infers the
         increment from the commit history (a `feat` yields a minor, a
         `BREAKING CHANGE` a major). --part overrides that inference.
      4. Create a release commit + a signed vX.Y.Z tag
      5. Push the commit AND the tag to origin/main
      6. The tag automatically triggers the GitHub Actions release.yml workflow
         which builds, publishes to PyPI, and creates the GitHub Release.

    Usage:
        inv release                  # increment inferred from the commits
        inv release --part=patch     # force patch (0.1.0 → 0.1.1)
        inv release --part=minor     # force minor (0.1.0 → 0.2.0)
        inv release --part=major     # force major (0.1.0 → 1.0.0)
        inv release --dry-run        # simulate without modifying anything
        inv release --skip-tests     # for local development only
    """

    def _run(cmd: str, check: bool = True) -> int:
        """Execute a shell command, display the result, return the exit code."""
        if dry_run:
            print(f"[dry-run] {cmd}")
            return 0
        result = subprocess.run(cmd, shell=True)
        if check and result.returncode != 0:
            print(f"\n\u274c Failed: {cmd}")
            raise SystemExit(result.returncode)
        return result.returncode

    print("\n🔍 Release workflow")
    print(f"  Bump type  : {part or 'inferred from commits'}")
    print(f"  Dry run    : {dry_run}")
    print(f"  Branch     : {RELEASE_BRANCH}")

    # ── Step 0: pre-flight checks ─────────────────────────────────────────────
    print("\n📦 Step 1/5: pre-flight checks...")

    # Current branch
    current_branch = subprocess.run(
        "git rev-parse --abbrev-ref HEAD", shell=True, capture_output=True, text=True
    ).stdout.strip()
    if not dry_run and current_branch != RELEASE_BRANCH:
        print(f"❌ You are on '{current_branch}', not on '{RELEASE_BRANCH}'.")
        print(f"   Run 'git checkout {RELEASE_BRANCH}' before releasing.")
        raise SystemExit(1)

    # Clean working tree
    dirty = subprocess.run(
        "git status --porcelain", shell=True, capture_output=True, text=True
    ).stdout.strip()
    if not dry_run and dirty:
        print("❌ Working tree is not clean. Commit or stash first.")
        print(dirty)
        raise SystemExit(1)

    print("✅ Branch and working tree OK")

    # ── Step 1: lint + tests ──────────────────────────────────────────────────
    if not skip_tests:
        print("\n📦 Step 2/5: lint + tests...")
        _run("uv run pre-commit run --all-files")
        _run("uv run python -m pytest --cov-fail-under=85 -q")
        print("✅ Lint and tests OK")
    else:
        print("\n⚠️  Step 2/5: lint + tests skipped (--skip-tests)")

    # ── Step 2: bump version + changelog ─────────────────────────────────────
    print(f"\n📦 Step 3/5: bump version ({part or 'inferred'})...")
    # Sans --part, on laisse commitizen déduire l'incrément de l'historique :
    # forcer --increment ferait passer un `feat!` en patch si le flag était
    # oublié, sous-versionnant silencieusement un breaking change.
    #
    # --no-verify : lint et tests ont déjà tourné à l'étape 2/5. Rejouer les hooks
    # sur le commit de version est redondant, et le `uv run` du hook mypy
    # réécrit uv.lock avec la version fraîchement bumpée : pre-commit voit un
    # fichier modifié après coup, refuse le commit, et la release échoue à
    # mi-parcours (fichiers bumpés, aucun commit, aucun tag).
    bump_cmd = "uv run cz bump --no-verify"
    if part:
        bump_cmd += f" --increment {part.upper()}"
    if dry_run:
        bump_cmd += " --dry-run"
        # cz bump --dry-run is itself non-destructive, so run it directly
        # instead of letting _run swallow it — this is what actually surfaces
        # the target version + changelog preview.
        preview = subprocess.run(bump_cmd, shell=True)
        if preview.returncode != 0:
            print(f"\n❌ Failed: {bump_cmd}")
            raise SystemExit(preview.returncode)
    else:
        _run(bump_cmd)
    print("✅ Version bumped + CHANGELOG.md updated")

    # Get the new version after the bump. In dry-run nothing was actually
    # bumped, so this is still the current version — don't mislabel it as new.
    new_version = subprocess.run(
        "uv run cz version --project", shell=True, capture_output=True, text=True
    ).stdout.strip()
    if not dry_run:
        print(f"   New version: {new_version}")

    # ── Step 3: push commit + tag ─────────────────────────────────────────────
    print("\n📦 Step 4/5: push commit + tag...")
    _run(f"git push origin {RELEASE_BRANCH}")
    _run(f"git push origin v{new_version}")
    print("✅ Commit + tag pushed")

    # ── Step 4: summary ───────────────────────────────────────────────────────
    print("\n📦 Step 5/5: summary...")
    print(f"🎉 Release v{new_version} launched!")
    print("   → GitHub Actions release.yml will build and publish to PyPI")
    print("   → Follow at: https://github.com/mattdav/okflint/actions")
    if not dry_run:
        print(f"   → PyPI: https://pypi.org/project/okflint/{new_version}/")
